### ISSUE TITLE
Details for why BFQ was removed?

### ISSUE THREAD

**Issue by polarathene** [torvic9/linux49-vd#5]
Not an issue, just curious why BFQ was removed. I didn't see any explanation in the related commit or README that mentions it. I know that with kernels after 4.8 on stock Manjaro I have some BFQ bugs that hard lock my system, was it due to these bugs?

**Comment by torvic9** [comment]
In some ways yes, bfq had some problems in the past, that's why I removed it.
However, there is a "with-bfq" branch that includes bfq. You might checkout that branch if you want to use bfq. By the way, wait till later today before you compile, there's an issue with a patch (see other issue here). I'll fix it later.
